project: "ModelForge Churn Prediction"
version: "2.0"

data:
  raw_path: "data/raw/churn.csv"
  processed_path: "data/processed/churn_engineered.parquet"
  target_col: "churn"

features:
  numeric: ["age", "income", "support_calls"]
  categorical: ["city", "plan_type", "device"]

model:
  estimator: "XGBoostClassifier"  # Also supports: "RandomForest", "LightGBM", "LogisticRegression"
  param_grid:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7]
    learning_rate: [0.05, 0.1, 0.2]

training:
  test_size: 0.2
  cv_folds: 5
  scoring: "roc_auc"
  random_state: 42

monitoring:
  drift_threshold: 0.2
  trigger_retrain: true
  report_dir: "data/drift_reports"

deployment:
  model_name: "ChurnPredictionModel"
  default_stage: "Staging"
  production_stage: "Production"
  api_port: 8000
  rate_limit: 100  # requests per minute

infrastructure:
  tracking_uri: "http://mlflow:5000"   # For Docker/K8s
  artifact_uri: "s3://ml-artifacts"   # Optional S3
