name: Train & Deploy

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Training Pipeline
        run: python main.py
        env:
          MLFLOW_TRACKING_URI: http://mlflow:5000  # or use self-hosted
      - name: Upload Drift Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: drift-report
          path: data/drift_reports/

  deploy:
    needs: train
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          cd app
          docker build -t model-forge-api:$GITHUB_SHA .
      - name: Push to DockerHub (optional)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag model-forge-api:$GITHUB_SHA your-dockerhub/model-forge-api:latest
          docker push your-dockerhub/model-forge-api:latest
